CREATE TABLE translation
(
    key VARCHAR(255) PRIMARY KEY,
    english VARCHAR(255) NOT NULL,
    dutch VARCHAR(255) NOT NULL
);


INSERT INTO translation (key, english, dutch) VALUES
('Home', 'Home', 'Home'),
('Projects', 'Projects', 'Projecten'),
('Collaborators', 'Collaborators', 'Medewerkers'),
('Research Groups', 'Research Groups', 'Onderzoeksgroepen'),
('Research Group', 'Research Group', 'Onderzoeksgroep'),
('Contact', 'Contact', 'Contact'),
('Send', 'Send', 'Verzend'),
('Your message', 'Your message', 'Uw bericht'),
('First Name', 'First Name', 'Voornaam'),
('Last Name', 'Last Name', 'Achternaam'),
('Employee', 'Employee', 'Werknemer'),
('Contact Message', 'Contact the administrators of the ESP system by entering your name and a message', 'Contacteer de administrators van het ESP systeem door je naam en een bericht in te geven'),
('Username', 'Username', 'Gebruikersnaam'),
('Short username', 'Short username', 'Korte gebruikersnaam'),
('Password', 'Password', 'Wachtwoord'),
('Wrong syntax', 'Please use your short username. It does not contain any @, \\ or .', 'Gelieve uw korte gebruikersnaam op te geven. Deze bevat geen @, \\ of .'),
('Login', 'Login', 'Aanmelden'),
('Logout', 'Logout', 'Afmelden'),
('Home Page', 'Home Page', 'Home Pagina'),
('Contact page', 'Contact page', 'Contact pagina'),
('Manage', 'Manage', 'Beheer'),
('Supporting Lists', 'Supporting Lists', 'Ondersteunende Lijsten'),
('Register', 'Register', 'Registreer'),
('Registrations', 'Registrations', 'Registraties'),
('Supervisor', 'Supervisors', 'Begeleiders'),
('Description', 'Description', 'Beschrijving'),
('Address', 'Address', 'Adres'),
('Telephone number', 'Telephone nr', 'Telefoon nr'),
('Field of study', 'Field of study', 'Richting'),
('My Projects', 'My Projects', 'Mijn Projecten'),
('Attachments', 'Attachments', 'Bijlagen'),
('Liked Projects', 'Liked Projects', 'Opgeslagen Projecten'),
('Extend Projects', 'Extend Projects', 'Verleng Projecten'),
('New registration', 'New project registration', 'Nieuwe project registratie'),
('Contact Person', 'Contact Person', 'Contact Persoon'),
('Modify', 'Modify', 'Aanpassen'),
('Title', 'Title', 'Titel'),
('Number', 'Students', 'Studenten'),
('Employeetype', 'Employee type', 'Type medewerker'),
('Save', 'Save', 'Opslaan'),
('Add-Employee', 'Add employee', 'Werknemer toevoegen'),
('Generate-Tags', 'Add tags from description', 'Maak tags uit beschrijving'),
('Active-Project', 'Active project?', 'Actief project?'),
('Choose-Research-Group', 'Choose a research group', 'Kies een onderzoeksgroep'),
('Choose-Research-Groups', 'Choose one or more research groups', 'Kies een of meerdere onderzoeksgroepen'),
('Choose-Types', 'Choose one or more types', 'Kies een of meerdere types'),
('New-Tag', 'Write new tag here', 'Schrijf nieuwe tag hier'),
('Dropzone-Text', 'Click here or drop files here to upload.', 'Klik hier of sleep hier je bestanden om up te loaden'),
('New extension', 'Project extension needed', 'Project verlenging nodig'),
('Extend Text', 'Do you want to extend the project to the next year?', 'Wilt u dit project verlengen naar volgend jaar?'),
('Yes', 'Yes', 'Ja'),
('No', 'No', 'Nee'),
('Search', 'Search', 'Zoek'),
('Liked filter', 'Liked', 'Favorieten'),
('English filter', 'English', 'Engels'),
('Dutch filter', 'Dutch', 'Nederlands'),
('Sort filter', 'Sort on', 'Sorteren op'),
('Newest filter', 'Newest', 'Nieuwste'),
('Oldest filter', 'Oldest', 'Oudste'),
('Add project', 'Add Project', 'Voeg project toe'),
('Edit', 'Edit', 'Wijzig'),
('Select all', 'Select all', 'Selecteer alles'),
('Show descriptions', 'Show descriptions', 'Toon beschrijvingen'),
('All', 'All', 'Alle'),
('Add', 'Add', 'Voeg toe'),
('Remove', 'Remove', 'Verwijder'),
('Replace', 'Replace', 'Vervang'),
('Close', 'Close', 'Sluiten'),
('Save changes', 'Save changes', 'Sla veranderingen op'),
('Loading', 'Loading...', 'Laadt...'),
('My Profile', 'My Profile', 'Mijn Profiel'),
('Active status', 'Active status', 'Actief status'),
('Dont change', 'Don''t change', 'Verander niet'),
('Active', 'Active', 'Actief'),
('Non active', 'Non active', 'Non-actief'),
('All research groups', 'All research groups', 'Alle onderzoeksgroepen'),
('All years', 'All years', 'Alle jaren'),
('All types', 'All types', 'Alle types'),
('Light Theme', 'Light Theme', 'Licht Thema'),
('Dark Theme', 'Dark Theme', 'Donker Thema'),
('Show Inactive', 'Show Inactive', 'Toon Inactief'),
('Hide Inactive', 'Hide Inactive', 'Verberg Inactief'),
('Cookie notification', 'This website would like to use cookies', 'Deze website wil cookies gebruiken'),
('Cookie allow', 'Allow cookies', 'Cookies toestaan'),
('Cookie deny', 'No cookies', 'Geen cookies'),
('Add extern employee', 'Add extern employee', 'Externe medewerker toevoegen'),
('Most popular', 'Most popular', 'Populairste'),
('Like', 'Like', 'Bijhouden'),
('Unlike', 'Unlike', 'Niet bijhouden'),
('Recommended', 'Recommended', 'Aanbevolen'),
('results', 'result(s)', 'resulta(a)t(en)'),
('Extension confirmation', 'Are you sure you want to make all employees confirm if they want to continue their active projects?', 'Bent u zeker dat u alle werknemers wilt laten bevestigen of ze hun actieve projecten willen verlengen?'),
('Title error', 'There is no title given.', 'Er is geen titel ingevoerd. '),
('Studentamount error', 'There is no amount of students given.', 'Er is geen hoeveelheid studenten ingevoerd. '),
('Researchgroup error', 'There is no researchgroup given.', 'Er is geen onderzoeksgroep ingevoerd. '),
('Promotor error', 'There is an invalid employee in the promotor list.', 'Er is een ongeldige medewerker in de lijst met promotoren.'),
('Co-promotor error', 'There is an invalid employee in the co-promotor list.', 'Er is een ongeldige medewerker in de lijst met co-promotoren.'),
('Mentor error', 'There is an invalid employee in the mentor list.', 'Er is een ongeldige medewerker in de lijst met begeleiders.'),
('Description error', 'There is no description given.', 'Er is geen beschrijving ingevoerd.'),
('Employeetype error', 'There is no employee type selected.', 'Er is geen medewerkerstype geselecteerd.'),
('Registration confirmation', '<strong>Success!</strong> Your registration is sent! You will be notified of any changes.', '<strong>Succes!</strong> De registratie is verzonden! U zal verwittigd worden van eventuele wijzigingen.'),
('show full', 'Show full', 'Toon volle'),
('projectSavedMessage', 'Project saved', 'Project opgeslagen'),
('project-csv', 'Download Report', 'Download Rapport'),
('Overview', 'Overview', 'Overzicht'),
('Generate', 'Generate overview', 'Genereer overzicht'),
('Copy', 'Copy', 'Kopiëer'),
('Delete', 'Delete', 'Verwijder'),
('Bulk Edit', 'Bulk Edit', 'Bulk Edit'),
('Research', 'Research', 'Onderzoek'),
('Career', 'Career', 'Carrière'),
('Company Name', 'Company Name', 'Bedrijfsnaam'),
('Contact Person Name', 'Contact Person Name', 'Contactpersoon Naam'),
('Contact Person Email', 'Contact Person Email', 'Contactpersoon Email'),
('Title of the Internship', 'Title of the Internship', 'Titel van de Stage'),
('Create Internship', 'Create Internship', 'Maak Stage aan'),
('Title of the internship', 'Title of the internship', 'Titel van de stage'),
('Create Internship Application', 'Internship Application', 'Aanvraag Stageopdracht'),
('Create Event', 'Create Event', 'Maak Evenement aan'),
('Event Name', 'Event Name', 'Naam Evenement'),
('Event Date', 'Event Date', 'Datum Evenement'),
('Event Type', 'Event Type', 'Type Evenement'),
('Start Date', 'Start Date', 'Startdatum'),
('End Date', 'End Date', 'Einddatum'),
('Event Title', 'Event Title', 'Titel Evenement'),
('Website', 'Website', 'Website'),
('Create New Event', 'Create New Event', 'Maak nieuw evenement aan'),
('Tags', 'Tags', 'Tags'),
('Internship', 'Internship', 'Stage'),
('Vacature', 'Vacancy', 'Vacature'),
('Job Fair', 'Job Fair', 'Jobbeurs'),
('Conference', 'Conference', 'Conferentie'),
('Event', 'Event', 'Evenement'),
('Event Description', 'Event Description', 'Evenement Beschrijving'),
('Thesis', 'Thesis', 'Thesis'),
('Webinair', 'Webinar', 'Webinair'),
('Calendar', 'Calendar', 'Kalender');
